version: '3'
services:
  app:
    container_name: doj-server
    environment:
      - MONGODB_URI=mongodb://doj-server-mongo:27017/doj-server
    restart: always
    build: .
    ports:
      - '80:3000'
    links:
      - mongo
  mongo:
    container_name: doj-server-mongo
    image: mongo
    ports:
      - '27017:27017'